AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true

Documentation:
  Enabled: false

# Uncomment in order to use byebug.
# Lint/Debugger:
#   Enabled: false

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false
